version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker-network
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb

volumes:
  mariadb:
  wordpress:

networks:
  docker-network:
    driver: bridge