version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker-network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker-network
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - docker-network
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  docker-network:
    driver: bridge